# -*- coding: utf-8 -*-

GPmap = {
 ur"モーセ" : "Moses",
 ur"マハーヴィーラ" : "Mahavira",
 ur"ゾロアスター" : "Zoroaster",
 ur"アーナンダ" : "Ananda",
 ur"荘子" : "Chuang-Tzu",
 ur"孟子" : "Mencius",
 ur"墨子" : "Mo Tzu",
 ur"聖ヨハネ" : "St. John",
 ur"聖ペテロ" : "St. Peter",
 ur"聖パウロ" : "St. Paul",
 ur"ラビ・アキバ" : "Rabbi Akiva",
 ur"マニ" : "Mani",
 ur"聖アウグスティヌス" : "St. Augustine",
 ur"聖パトリック" : "St. Patrick",
 ur"アブー・バクル" : "Abu Bakr",
 ur"シャンカラ" : "Shankara",
 ur"弘法大師" : "Kobo-Daishi",
 ur"アティーシャ" : "Atisha",
 ur"聖トマス・アクィナス" : "St. Thomas Aquinas",
 ur"ムハンマド・シャー" : "Mohammed Shah",
 ur"ツォンカパ" : "Tsongkhapa",
 ur"ナラク" : "Narak",
 ur"ティプ・スルタン" : "Tipu Sultan",
 ur"ラーマクリシュナ" : "Ramakrishna",
 ur"ナーラーヤナ・グル" : "Narayana Guru",
 ur"ソジャーナ・トゥルース" : "Sojourner Truth",
 ur"卑弥呼" : "Himiko",
 ur"役小角" : "En no Gyoja",
 ur"鑑真" : "Jianzhen",
 ur"最澄" : "Saicho",
 ur"安部晴明" : "Abe no Seimei",
 ur"法然" : "Honen",
 ur"親鸞" : "Shinran",
 ur"蓮如" : "Rennyo",
 ur"栄西" : "Eisai",
 ur"道元" : "Dougen",
 ur"日蓮" : "Nichiren",
 ur"一休宗純" : "Ikkyu",
 ur"ペトロ・カスイ・岐部" : "Petro Kasui Kibe",
 ur"平田篤胤" : "Hirata Atsutane",
 ur"内村鑑三" : "Uchimura Kanzo",
 ur"鈴木大拙" : "Suzuki Daisetsu",
 ur"龍樹" : "Nagarjuna",
 ur"弥勒" : "Maitreya",
 ur"無著" : "Asanga",
 ur"世親" : "Vasubandhu",
 ur"鳩摩羅什" : "Kumarajiva",
 ur"達磨" : "Bodhidharma",
 ur"安世高" : "An Shigao",
 ur"釈道安" : "Dao An",
 ur"玄奘三蔵" : "Xuanzang",
 ur"ソンツェン・ガンポ" : "Songtsan Gampo",
 ur"スーナム・ギャツォ" : "Sonam Gyatso",
 ur"リタイ" : "Lithai",
 ur"ビームラーオ・Ｒ・アンベードカル" : "Bhimrao R.Ambedkar",
 ur"プッタタート" : "Buddhadasa",
 ur"大アントニオス" : "Anthony the Great",
 ur"聖金口イオアン" : "St. Ioannes Chrysostomos",
 ur"聖フルメンティウス" : "St. Frumentius",
 ur"ネストリウス" : "Nestorius",
 ur"聖イオアン" : "St. Ioan",
 ur"聖メトディオス" : "St. Methodius",
 ur"聖キュリロス" : "St. Kyrillos",
 ur"聖イヴァン" : "St. Ivan Rilski",
 ur"トマス・ベケット" : "Thomas Becket",
 ur"ゲブレ・メスケル・ラリベラ" : "Gebre Mesqel Lalibela",
 ur"聖フランチェスコ" : "Francesco d'Assisi",
 ur"マイスター・エックハルト" : "Meister Eckhart",
 ur"聖セルギイ" : "St. Sergius",
 ur"ヤン・フス" : "Jan Hus",
 ur"マルティン・ルター" : "Martin Luther",
 ur"フルドリッヒ・ツヴィングリ" : "Huldrych Zwingli",
 ur"ジャン・カルヴァン" : "Jean Calvin",
 ur"ラス・カサス" : "las Casas",
 ur"フランシスコ・ザビエル" : "Francisco de Xavier",
 ur"ウィリアム・ブラッドフォード" : "William Bradford",
 ur"エマヌエル・スヴェーデンボリ" : "Emanuel Swedenborg",
 ur"ジョン・ウェスレー" : "John Wesley",
 ur"聖セラフィム" : "St. Seraphim",
 ur"セーレン・キェルケゴール" : "Soren Kierkegaard",
 ur"チャールズ・スポルジョン" : "Charles Spurgeon",
 ur"カール・バルト" : "Karl Barth",
 ur"パウル・ティリッヒ" : "Paul Tillich",
 ur"ディートリッヒ・ボンヘッファー" : "Dietrich Bonhoeffer",
 ur"マザー・テレサ" : "Mother Teresa",
 ur"マーティン・ルーサー・キング・Ｊｒ" : "Martin Luther King,Jr.",
 ur"アル＝ブハーリー" : "al-Bukhari",
 ur"タバリー" : "al-Tabari",
 ur"アシュアリー" : "Ash'ari",
 ur"アル・ガザーリー" : "Al-Ghazali",
 ur"モッラー・サドラー" : "Mulla Sadra",
 ur"アフガーニー" : "Jamal-al-Din Afghani",
 ur"ムハンマド・アブドゥフ" : "Muhammad Abduh",
 ur"ラシード・リダー" : "Rashid Rida",
 ur"ヤージュニャヴァルキヤ" : "Yajnavalkya",
 ur"パタンジャリ" : "Patanjali",
 ur"ラーマーヌジャ" : "Ramanuja",
 ur"ラーマーナンダ" : "Ramananda",
 ur"カビール" : "Kabir",
 ur"ヴィヴェーカーナンダ" : "Swami Vivekananda",
 ur"オーロビンド・ゴーシュ" : "Sri Aurobindo",
 ur"エゼキエル" : "Ezekiel",
 ur"イェフーダー・ハン＝ナーシー" : "Judah haNasi",
 ur"モーシェ・ベン＝マイモーン" : "Moshe ben Maimon",
 ur"モーゼス・デ・レオン" : "Moses de Leon",
 ur"テーオドール・ヘルツル" : "Theodor Herzl",
 ur"アクエンアテン" : "Akhenaten",
 ur"荀子" : "Xun Zi",
 ur"王陽明" : "Wang Yangming",
 ur"徐福" : "Xu Fu",
 ur"張陵" : "Zhang Daoling",
 ur"王重陽" : "Wang Chongyang",
 ur"丘長春" : "Qiu Chuji",
 ur"張三豊" : "Zhang Sanfeng",
 ur"陳王廷" : "Chen Wangting",
 ur"プロティノス" : "Plotinus",
 ur"カルティール" : "Kartir",
 ur"ココチュ・テブ・テングリ" : "Khokhcuu Teb-Tengri",
 ur"テノチ" : "Tenoch",
 ur"トラカエレル" : "Tlacaelel",
 ur"ジョン・ディー" : "John Dee",
 ur"フランソワ・マッカンダル" : "Francois Mackandal",
 ur"洪秀全" : "Hong Xiuquan",
 ur"クアナ・パーカー" : "Quanah Parker",
 ur"ウォヴォカ" : "Wovoka",
 ur"アレイスター・クロウリー" : "Aleister Crowley",
 ur"ジッドゥ・クリシュナムルティ" : "Jiddu Krishnamurti",
 ur"ボビー･ヘンダーソン" : "Bobby Henderson",

 ur"ホメロス" : "Homer",
 ur"テスピス" : "Thespis",
 ur"伶倫" : "Ling Lun",
 ur"王羲之" : "Wang Xizhi",
 ur"ヴァールミーキ" : "Valmiki",
 ur"ウェルギリウス" : "Virgil",
 ur"カーリダーサ" : "Kalidas",
 ur"李白" : "Li Po",
 ur"杜甫" : "Du Fu",
 ur"ジャラール・アル・ディーン・ルーミー" : "Jalal al-Din Rumi",
 ur"ダンテ・アリギエリ" : "Dante Alighieri",
 ur"ユーヌス・エムレ" : "Yunus Emre",
 ur"アミール・ホスロー" : "Amir Khusro",
 ur"イブン・ムクラ" : "Ibn Muqlah",
 ur"ミケランジェロ" : "Michaelangelo",
 ur"ラファエロ" : "Raphael",
 ur"ウィリアム・シェイクスピア" : "William Shakespeare",
 ur"ミゲル・デ・セルバンテス" : "Miguel de Cervantes",
 ur"レンブラント・ ファン・レイン" : "Rembrandt van Rijn",
 ur"ヨハネス・フェルメール" : "Johannes Vermeer",
 ur"J・S・バッハ" : "J. S. Bach",
 ur"ヴォルフガング・アマデウス・モーツァルト" : "Wolfgang Amadeus Mozart",
 ur"ヨハン・ヴォルフガング・フォン・ゲーテ" : "Johann Wolfgang von Goethe",
 ur"ルートヴィヒ・ヴァン・ベートーヴェン" : "Ludwig van Beethoven",
 ur"ヴィクトル・ユゴー" : "Victor Hugo",
 ur"フィンセント・ファン・ゴッホ" : "Vincent van Gogh",
 ur"ヨハネス・ブラームス" : "Johannes Brahms",
 ur"アントニン・ドヴォルザーク" : "Antonin Dvorak",
 ur"マーク・トウェイン" : "Mark Twain",
 ur"クロード・モネ" : "Claude Monet",
 ur"ジョゼフ・コンラッド" : "Joseph Conrad",
 ur"フランツ・カフカ" : "Frank Kafka",
 ur"ルイ・アームストロング" : "Louis Armstrong",
 ur"デューク・エリントン" : "Duke Ellington",
 ur"パブロ・ピカソ" : "Pablo Picasso",
 ur"マイルス・デイヴィス" : "Miles Davis",
 ur"紫式部" : "Murasaki Shikibu",
 ur"観阿弥" : "Kanami",
 ur"世阿弥" : "Zeami",
 ur"雪舟" : "Sesshu",
 ur"池坊専応" : "Ikenobo Senou",
 ur"千利休" : "Sen no Rikyu",
 ur"出雲阿国" : "Izumo no Okuni",
 ur"松尾芭蕉" : "Matsuo Basho",
 ur"葛飾北斎" : "Katsushika Hokusai",
 ur"岡倉天心" : "Okakura Tenshin",
 ur"柳宗悦" : "Yanagi Soetsu",
 ur"北大路魯山人" : "Kitaooji Rosanjin",
 ur"宮沢賢治" : "Miyazawa Kenji",
 ur"川端康成" : "Kawabata Yasunari",
 ur"勅使河原蒼風" : "Teshigahara Sofu",
 ur"李香蘭" : "Li Xianglan",
 ur"三島由紀夫" : "Mishima Yukio",
 ur"手塚治虫" : "Tezuka Osamu",
 ur"黒澤明" : "Kurosawa Akira",
 ur"陸羽" : "Lu Yu",
 ur"アントナン・カレーム" : "Marie-Antoine Careme",
 ur"Ｊ・Ｅ・ロベール＝ウーダン" : "J･E･Robert-Houdin",
 ur"マリウス・プティパ" : "Marius Petipa",
 ur"セルゲイ・ディアギレフ" : "Sergei Diaghilev",
 ur"ハリー・フーディーニ" : "Harry Houdini",
 ur"イサドラ・ダンカン" : "Isadora Duncan",
 ur"ヴァーツラフ・ニジンスキー" : "Vaslav Nijinsky",
 ur"アルフレッド・スティーグリッツ" : "Alfred Stieglitz",
 ur"マルセル・デュシャン" : "Marcel Duchamp",
 ur"アンディ・ウォーホル" : "Andy Warhol",
 ur"ベッシー・スミス" : "Bessie Smith",
 ur"ジャンゴ・ラインハルト" : "Django Reinhardt",
 ur"レイ・チャールズ" : "Ray Charles",
 ur"エルヴィス・プレスリー" : "Elvis Presley",
 ur"ジョン・レノン" : "John Lennon",
 ur"ジミ・ヘンドリクス" : "Jimi Hendrix",
 ur"ボブ・マーリー" : "Bob Marley",
 ur"フレディ・マーキュリー" : "Freddie Mercury",
 ur"マイケル・ジャクソン" : "Michael Jackson",
 ur"チャールズ・チャップリン" : "Charlie Chaplin",
 ur"マーロン・ブランド" : "Marlon Brando",
 ur"マリリン・モンロー" : "Marilyn Monroe",
 ur"オードリー・ヘプバーン" : "Audrey Hepburn",
 ur"李小龍" : "Bruce Lee",
 ur"セルゲイ・エイゼンシュテイン" : "Sergei Eisenstein",
 ur"アルフレッド・ヒッチコック" : "Alfred Hitchcock",
 ur"ウォルト・ディズニー" : "Walt Disney",
 ur"レニ・リーフェンシュタール" : "Leni Riefenstahl",
 ur"スタンリー・キューブリック" : "Stanley Kubrick",
 ur"アンドレイ・タルコフスキー" : "Andrei Tarkovsky",
 ur"シド・マイヤー" : "Sid Meier",
 ur"ペイディアス" : "Pheidias",
 ur"顧ガイ之" : "Gu Kaizhi",
 ur"沈周" : "Shen Zhou",
 ur"シャルル・ル・ブラン" : "Charles Le Brun",
 ur"フランシスコ・デ・ゴヤ" : "Francisco Goya",
 ur"オーギュスト・ロダン" : "Auguste Rodin",
 ur"アルフォンス・ムハ" : "Alphonse Mucha",
 ur"エドヴァルド・ムンク" : "Edvard Munch",
 ur"ワシリー・カンディンスキー" : "Wassily Kandinsky",
 ur"マウリッツ・エッシャー" : "Maurits Escher",
 ur"サルバドール・ダリ" : "Salvador Dali",
 ur"ヨハン・パッヘルベル" : "Johann Pachelbel",
 ur"ニコロ・パガニーニ" : "Niccolo Paganini",
 ur"フランツ・シューベルト" : "Franz Schubert",
 ur"フレデリック・ショパン" : "Frederic Chopin",
 ur"フランツ・リスト" : "Franz Liszt",
 ur"リヒャルト・ワーグナー" : "Richard Wagner",
 ur"ピョートル・チャイコフスキー" : "Pyotr Tchaikovsky",
 ur"エドワード・エルガー" : "Edward Elgar",
 ur"パウル・ヒンデミット" : "Paul Hindemith",
 ur"エリック・サティ" : "Erik Satie",
 ur"パブロ・カザルス" : "Pablo Casals",
 ur"イーゴリ・ストラヴィンスキー" : "Igor Stravinsky",
 ur"ジョージ・ガーシュウィン" : "George Gershwin",
 ur"ヤッシャ・ハイフェッツ" : "Jascha Heifetz",
 ur"ウラディミール・ホロヴィッツ" : "Vladimir Horowitz",
 ur"ドミートリイ・ショスタコーヴィチ" : "Dmitri Shostakovich",
 ur"ルチアーノ・パヴァロッティ" : "Luciano Pavarotti",
 ur"アルトゥーロ・トスカニーニ" : "Arturo Toscanini",
 ur"ブルーノ・ヴァルター" : "Bruno Walter",
 ur"レオポルド・ストコフスキー" : "Leopold Stokowski",
 ur"ヴィルヘルム・フルトヴェングラー" : "Wilhelm Furtwangler",
 ur"カール・ベーム" : "Karl Bohm",
 ur"エフゲニー・ムラヴィンスキー" : "Yevgeny Mravinsky",
 ur"ヘルベルト・フォン・カラヤン" : "Herbert von Karajan",
 ur"レナード・バーンスタイン" : "Leonard Bernstein",
 ur"カルロス・クライバー" : "Carlos Kleiber",
 ur"サッフォー" : "Sappho",
 ur"曹植" : "Cao Zhi",
 ur"アブー・ヌワース" : "Abu Nuwas",
 ur"白居易" : "Bai Juyi",
 ur"フェルドウスィー" : "Ferdowsi",
 ur"ユースフ・ハーッス・ハージブ" : "Yusuf Balasaghuni",
 ur"スノッリ・ストゥルルソン" : "Snorri Sturluson",
 ur"許蘭雪軒" : "Heo Nanseolheon",
 ur"フリードリヒ・フォン・シラー" : "Friedrich von Schiller",
 ur"シャルル・ボードレール" : "Charles Baudelaire",
 ur"ラビンドラナート・タゴール" : "Rabindranath Tagore",
 ur"アイソーポス" : "Aisopos",
 ur"テュロルド" : "Turoldus",
 ur"羅貫中" : "Luo Guanzhong",
 ur"許イン" : "Heo Gyun",
 ur"崔南善" : "Choe Nam-seon",
 ur"李光洙" : "Lee Kwang-su",
 ur"アレクサンドル・デュマ" : "Alexandre Dumas",
 ur"ハンス・クリスチャン・アンデルセン" : "Hans Christian Andersen",
 ur"エリアス・リョンロート" : "Elias Lonnrot",
 ur"フョードル・ドストエフスキー" : "Fyodor Dostoyevsky",
 ur"レフ・トルストイ" : "Leo Tolstoy",
 ur"魯迅" : "Lu Xun",
 ur"ローラ・インガルス・ワイルダー" : "Laura Ingalls Wilder",
 ur"カレル・チャペック" : "Karel Capek",
 ur"ジョージ・バーナード・ショー" : "George Bernard Shaw",
 ur"アンブローズ・ビアス" : "Ambrose Bierce",
 ur"アーネスト・ヘミングウェイ" : "Ernest Hemingway",
 ur"Ｊ・Ｄ・サリンジャー" : "J.D.Salinger",
 ur"ジャン＝ポール・サルトル" : "Jean-Paul Sartre",
 ur"エドガー・アラン・ポー" : "Edgar Allan Poe",
 ur"アーサー・コナン・ドイル" : "Arthur Conan Doyle",
 ur"ジュール・ヴェルヌ" : "Jules Verne",
 ur"Ｈ・Ｇ・ウェルズ" : "H.G.Wells",
 ur"サン＝テグジュペリ" : "Saint-Exupery",
 ur"ルイス・キャロル" : "Lewis Carroll",
 ur"Ｈ・Ｐ・ラヴクラフト" : "H.P.Lovecraft",
 ur"Ｊ・Ｒ・Ｒ・トールキン" : "J.R.R.Tolkien",

 ur"メリト・プタハ" : "Merit Ptah",
 ur"ルイソ" : "Xi Ling Shi",
 ur"ナブリアヌー" : "Nabu-rimanni",
 ur"ソクラテス" : "Socrates",
 ur"プラトン" : "Plato",
 ur"アリストテレス" : "Aristole",
 ur"エウクレイデス" : "Euclid",
 ur"プトレマイオス" : "Ptolemy",
 ur"ヒュパティア" : "Hypatia",
 ur"祖冲之" : "Zu Chongzhi",
 ur"アールヤバタ" : "Aryabhata",
 ur"アル・キンディー" : "Al-Kindi",
 ur"アル・フワーリズミー" : "Al-Khwarizmi",
 ur"アル・ラジ" : "Al-Razi",
 ur"アルハーゼン" : "Alhazen",
 ur"ニコラウス・コペルニクス" : "Nicolaus Copernicus",
 ur"フランシス・ベーコン" : "Francis Bacon",
 ur"ティーコ・ブラーエ" : "Tycho Brahe",
 ur"ヨハネス・ケプラー" : "Johannes Kepler",
 ur"アイザック・ニュートン" : "Isaac Newton",
 ur"ガリレオ・ガリレイ" : "Galileo Galilei",
 ur"ルネ・デカルト" : "Rene Descartes",
 ur"アントニー・ファン・レーウェンフーク" : "Antony van Leeuwenhoek",
 ur"ゴットフリート・ライプニッツ" : "Gottfried Leibniz",
 ur"ミハイル・ロモノソフ" : "Mikhail Lomonosov",
 ur"アントワーヌ・ローラン・ラヴォアジェ" : "Antoine Laurent Lavoisier",
 ur"カール・フリードリヒ・ガウス" : "Carl Friedrich Gauss",
 ur"ジョン・ドルトン" : "John Dalton",
 ur"マイケル・ファラデー" : "Michael Faraday",
 ur"ジェームズ・クラーク・マクスウェル" : "James Clerk Maxwell",
 ur"ルイ・パストゥール" : "Louis Pasteur",
 ur"チャールズ・ダーウィン" : "Charles Darwin",
 ur"アーネスト・ラザフォード" : "Ernest Rutherford",
 ur"マリー・キュリー" : "Marie Curie",
 ur"アルバート・アインシュタイン" : "Albert Einstein",
 ur"ニールス・ボーア" : "Niels Bohr",
 ur"ウェルナー・ハイゼンベルク" : "Werner Heisenberg",
 ur"エンリコ・フェルミ" : "Enrico Fermi",
 ur"ロザリンド・フランクリン" : "Rosalind Franklin",
 ur"アンドレイ・サハロフ" : "Andrei Sakharov",
 ur"王仁" : "Wani",
 ur"関孝和" : "Seki Takakazu",
 ur"華岡青洲" : "Hanaoka Seishu",
 ur"北里柴三郎" : "Kitasato Shibasaburo",
 ur"南方熊楠" : "Minakata Kumagusu",
 ur"湯川秀樹" : "Yukawa Hideki",
 ur"伊藤清" : "Ito Kiyoshi",
 ur"ソロモン" : "Solomon",
 ur"アルクィン" : "Alcuin",
 ur"聖イシドールス" : "St. Isidorus",
 ur"聖フォティオス" : "St. Photios",
 ur"アルベルトゥス・マグヌス" : "Albertus Magnus",
 ur"フェデリコⅡ世" : "Frederick II",
 ur"パラケルスス" : "Paracelsus",
 ur"カール・フォン・リンネ" : "Carl Linnaeus",
 ur"レオンハルト・オイラー" : "Leonhard Euler",
 ur"ジョセフ＝ルイ・ラグランジュ" : "Joseph Louis Lagrange",
 ur"ピエール＝シモン・ラプラス" : "Pierre-Simon Laplace",
 ur"シクウォイア" : "Sequoyah",
 ur"ユストゥス・フォン・リービッヒ" : "Justus von Liebig",
 ur"エルンスト・マッハ" : "Ernst Mach",
 ur"グレゴール・メンデル" : "Gregor Mendel",
 ur"ロベルト・コッホ" : "Robert Koch",
 ur"コンスタンティン・ツィオルコフスキー" : "Konstantin Tsiolkovsky",
 ur"ルドヴィコ・ザメンホフ" : "L.L.Zamenhof",
 ur"フリッツ・ハーバー" : "Fritz Haber",
 ur"リーゼ・マイトナー" : "Lise Meitner",
 ur"アレクサンダー・フレミング" : "Alexander Fleming",
 ur"ロバート・オッペンハイマー" : "Robert Oppenheimer",
 ur"アラン・チューリング" : "Alan Turing",
 ur"ジョン・フォン・ノイマン" : "John von Neumann",
 ur"ジャービル・イブン＝ハイヤーン" : "Jabir ibn Hayyan",
 ur"フナイン・イブン・イスハーク" : "Hunayn ibn Ishaq",
 ur"アル＝ファーラービー" : "Al-Farabi",
 ur"アル＝ビールーニー" : "Abu Rayhan Biruni",
 ur"ナスィールッディーン・トゥースィー" : "Nasir al-Din al-Tusi",
 ur"イブン＝スィーナー" : "Ibn Sina",
 ur"ウマル・ハイヤーム" : "Omar Khayyam",
 ur"イブン・ルシュド" : "Ibn Rushd",
 ur"張機" : "Zhang Zhongjing",
 ur"葛洪" : "Ge Hong",
 ur"陶弘景" : "Tao Hongjing",
 ur"賈思キョウ" : "Jia Sixie",
 ur"李時珍" : "Li Shizhen",
 ur"徐光啓" : "Xu Guangqi",
 ur"許浚" : "Heo Jun",
 ur"朱熹" : "Zhu Xi",
 ur"鄭麟趾" : "Jeong In-ji",
 ur"シュリニヴァーサ・ラマヌジャン" : "Srinivasa Ramanujan",
 ur"ジャガディッシュ・チャンドラ・ボース" : "Jagadish Chandra Bose",

 ur"ハルクフ" : "Harkuf",
 ur"ハンノ" : "Hanno",
 ur"ピュテアス" : "Pytheas",
 ur"張騫" : "Zhang Qian",
 ur"アレタス3世" : "Aretas III",
 ur"レイフ・エリクソン" : "Leif Erickson",
 ur"王安石" : "Wang Anshi",
 ur"エンリコ・ダンドロ" : "Enrico Dandolo",
 ur"マルコ・ポーロ" : "Marco Polo",
 ur"イブン・バットゥータ" : "Ibn Battuta",
 ur"ディック・ホイッティントン" : "Richard Whittington",
 ur"ジョヴァンニ・デ・メディチ" : "Giovanni de Medici",
 ur"鄭和" : "Zheng He",
 ur"ヴァスコ・ダ・ガマ" : "Vasco da Gama",
 ur"クリストファー・コロンブス" : "Christopher Columbus",
 ur"フェルディナンド・マゼラン" : "Ferdinand Magellan",
 ur"ジャック・カルティエ" : "Jacques Cartier",
 ur"ラジャ・トダルマル" : "Raja Todar Mal",
 ur"アンソニー・ヴァン・ディーメン" : "Anthony van Diemen",
 ur"サー・トーマス・ロー" : "Sir Thomas Roe",
 ur"シャー・ジャハーン" : "Shah Jahan",
 ur"アダム・スミス" : "Adam Smith",
 ur"ジェームズ・クック" : "James Cook",
 ur"コーネリアス・ヴァンダービルト" : "Cornelius Vanderbilt",
 ur"サー・アレクサンダー・マッケンジー" : "Sir Alexander Mackenzie",
 ur"ジョン・スチュアート・ミル" : "John Stuart Mill",
 ur"アンドリュー・カーネギー" : "Andrew Carnegie",
 ur"ジョン・D・ロックフェラー" : "John D. Rockefeller",
 ur"ジョン・メイナード・ケインズ" : "John Maynard Keynes",
 ur"ココ・シャネル" : "Coco Chanel",
 ur"石田三成" : "Ishida Mitsunari",
 ur"山田長政" : "Yamada Nagamasa",
 ur"坂本龍馬" : "Sakamoto Ryoma",
 ur"渋沢栄一" : "Shibusawa Eiichi",
 ur"岩崎弥太郎" : "Iwasaki Yataro",
 ur"笹川良一" : "Sasakawa Ryoichi",
 ur"山田寅次郎" : "Yamada Torajiro",
 ur"豊田英二" : "Toyoda Eiji",
 ur"松下幸之助" : "Matsushita Konosuke",
 ur"山内溥" : "Yamauchi Hiroshi",
 ur"クロイソス" : "Croesus",
 ur"子貢" : "Zi Gong",
 ur"范蠡" : "Fan Li",
 ur"桑弘羊" : "Sang Hongyang",
 ur"張保皐" : "Jang Bogo",
 ur"セプティミウス・オダエナトゥス" : "Odaenathus",
 ur"蒲寿庚" : "Pu Shougeng",
 ur"エンリケ航海王子" : "Infante Dom Henrique",
 ur"アスキア・ムハンマド" : "Askia Mohammad",
 ur"アニケイ・ストロガノフ" : "Anikey Stroganov",
 ur"トーマス・グレシャム" : "Thomas Gresham",
 ur"張居正" : "Zhang Juzheng",
 ur"ヨーハン・ファン・オルデンバルネフェルト" : "Johan van Oldenbarnevelt",
 ur"ジョン・スミス" : "John Smith",
 ur"ジャン・バティスト・コルベール" : "Jean-Baptiste Colbert",
 ur"リヒテンシュタイン公ヨーハンⅡ世" : "Johann II",
 ur"モナコ大公ルイⅡ世" : "Louis II",
 ur"沈万三" : "Shen Wansan",
 ur"アメリゴ・ヴェスプッチ" : "Amerigo Vespucci",
 ur"ヤコブ・フッガー" : "Jakob Fugger",
 ur"王直" : "Wang Zhi",
 ur"エドワード・ロイド" : "Edward Lloyd",
 ur"ネイサン・ロスチャイルド" : "Nathan Rothschild",
 ur"アーサー・ギネス" : "Arthur Guinness",
 ur"リチャード・アークライト" : "Richard Arkwright",
 ur"アルフレート・クルップ" : "Alfred Krupp",
 ur"ジャムジェトジ・タタ" : "Jamsetji Tata",
 ur"ジェイコブ・シフ" : "Jacob Schiff",
 ur"ウィリアム・Ｃ・デュラント" : "William C.Durant",
 ur"ロバート・ウッドラフ" : "Robert W.Woodruff",
 ur"エンツォ・フェラーリ" : "Enzo Ferrari",
 ur"レイ・クロック" : "Raymond Kroc",
 ur"アリストテレス・オナシス" : "Aristotle Onassis",
 ur"スティーブ・ジョブズ" : "Steve Jobs",
 ur"桑弘羊" : "Sang Hongyang",
 ur"フィロン" : "Philon",
 ur"赤毛のエイリーク" : "Erik the Red",
 ur"サミュエル・ド・シャンプラン" : "Samuel de Champlain",
 ur"エヴリヤ・チェレビ" : "Evliya Celebi",
 ur"デヴィッド・リカード" : "David Ricardo",
 ur"フリードリヒ・ハイエク" : "Friedrich Hayek",
 ur"甘英" : "Gan Ying",

 ur"イムホテプ" : "Imhotep",
 ur"アルキメデス" : "Archimedes",
 ur"ヘロン" : "Heron",
 ur"蔡倫" : "Cai Lun",
 ur"張衡" : "Zhang Heng",
 ur"畢昇" : "Bi Sheng",
 ur"レオナルド・ダ・ヴィンチ" : "Leonardo da Vinci",
 ur"シナン" : "Sinan",
 ur"ヴィルヘルム・シッカルト" : "Wilhelm Schickard",
 ur"ブレーズ・パスカル" : "Blaise Pascal",
 ur"ベンジャミン・フランクリン" : "Benjamin Franklin",
 ur"シャルル・オーギュスタン・ド・クーロン" : "Charles Augustin de Coulomb",
 ur"ジェームズ・ワット" : "James Watt",
 ur"ジョセフ・マリー・ジャカール" : "Joseph Marie Jacquard",
 ur"イザムバード・キングダム・ブルネル" : "Isambard Kingdom Brunel",
 ur"ウィリアム・T・G・モートン" : "William T. G. Morton",
 ur"ルイ・ダゲール" : "Louis Daguerre",
 ur"フェルディナン・ド・レセップス" : "Ferdinand de Lesseps",
 ur"ジョン・ローブリング" : "John Roebling",
 ur"ノルベルト・リリュー" : "Norbert Rillieux",
 ur"ヘンリー・ベッセマー" : "Henry Bessemer",
 ur"ナイン・シン" : "Nain Singh",
 ur"アレクサンダー・グラハム・ベル" : "Alexander Graham Bell",
 ur"ニコラス・アウグスト・オットー" : "Nikolaus August Otto",
 ur"ニコラ・テスラ" : "Nichola Tesla",
 ur"トーマス・エジソン" : "Thomas Edison",
 ur"グリエルモ・マルコーニ" : "Guglielmo Marconi",
 ur"アレクサンダー・ギュスターヴ・エッフェル" : "Alexandre Gustave Eiffel",
 ur"ジョージ・ワシントン・ゴーサルズ" : "George Washington Goethals",
 ur"ヘンリー・フォード" : "Henry Ford",
 ur"ウィルバー・ライト" : "Wilbur Wright",
 ur"オーヴィル・ライト" : "Orville Wright",
 ur"国中公麻呂" : "Kuninaka no Kimimaro",
 ur"正宗" : "Masamune",
 ur"李参平" : "Yi Sam-pyeong",
 ur"平賀源内" : "Hiraga Gennai",
 ur"田中久重" : "Tanaka Hisashige",
 ur"豊田佐吉" : "Toyoda Sakichi",
 ur"八木秀次" : "Yagi Hidetsugu",
 ur"本多光太郎" : "Honda Kotaro",
 ur"内藤多仲" : "Naito Tachu",
 ur"島秀雄" : "Shima Hideo",
 ur"本田宗一郎" : "Honda Soichiro",
 ur"井深大" : "Ibuka Masaru",
 ur"高柳健次郎" : "Takayanagi Kenjiro",
 ur"アッバース・イブン・フィルナス" : "Abbas Ibn Firnas",
 ur"ヘザルフェン・アフメト・チェレビ" : "Hezarfen Ahmed Celebi",
 ur"ラガリ・ハサン・チェレビ" : "Lagari Hasan celebi",
 ur"オットー・リリエンタール" : "Otto Lilienthal",
 ur"アルベルト・サントス・デュモン" : "Alberto Santos-Dumont",
 ur"イーゴリ・シコールスキイ" : "Igor Sikorsky",
 ur"ジャック・ノースロップ" : "Jack Northrop",
 ur"ウィリー・メッサーシュミット" : "Willy Messerschmitt",
 ur"セルゲイ・コロリョフ" : "Sergey Korolyov",
 ur"ヴェルナー・フォン・ブラウン" : "Wernher von Braun",
 ur"マクシム・ファゲット" : "Maxime Faget",
 ur"リチャード・トレビシック" : "Richard Trevithick",
 ur"ジョージ・スチーブンソン" : "George Stephenson",
 ur"ゴッドリープ・ダイムラー" : "Gottlieb Daimler",
 ur"カール・ベンツ" : "Karl Benz",
 ur"ルドルフ・ディーゼル" : "Rudolf Diesel",
 ur"フェルディナンド・ポルシェ" : "Ferdinand Porsche",
 ur"ロバート・フルトン" : "Robert Fulton",
 ur"クリストファー・コッカレル" : "Christopher Cockerell",
 ur"ヨハネス・グーテンベルグ" : "Johannes Gutenberg",
 ur"チャールズ・バベッジ" : "Charles Babbage",
 ur"ジョセフ・ヘンリー" : "Joseph Henry",
 ur"レジナルド・フェッセンデン" : "Reginald Fessenden",
 ur"ウィリアム・ショックレー" : "William Shockley",
 ur"カリクラテス" : "Kallikrates",
 ur"アッピウス・クラウディウス・カエクス" : "Appius Claudius Caecus",
 ur"ウィトルウィウス" : "Vitruvius",
 ur"イシドロス" : "Isidoros",
 ur"郭守敬" : "Guo Shoujing",
 ur"ドナト・ブラマンテ" : "Donato Bramante",
 ur"クリストファー・レン" : "Christopher Wren",
 ur"ジュール・アルドゥアン＝マンサール" : "Jules Hardouin Mansart",
 ur"コンスタンチン・トーン" : "Konstantin Thon",
 ur"フレデリック・ロー・オルムステッド" : "Frederick Law Olmsted",
 ur"アントニ・ガウディ" : "Antoni Gaudi",
 ur"オーギュスト・ペレ" : "Auguste Perret",
 ur"ルシオ・コスタ" : "Lucio Costa",
 ur"オスカー・ニーマイヤー" : "Oscar Niemeyer",
 ur"ヨーン・ウツソン" : "Jorn Utzon",
 ur"馬鈞" : "Ma Jun",
 ur"ウルバン" : "Urban",
 ur"イーライ・ホイットニー" : "Eli Whitney Jr",
 ur"アルフレッド・ノーベル" : "Alfred Nobel",
 ur"ヴィルヘルム・レントゲン" : "Wilhelm Rontgen",
 ur"ジョン・ブローニング" : "John Browning",

 ur"サルゴン" : "Sargon",
 ur"ネブカドネザル２世" : "Nebuchadrezzar II",
 ur"孫子" : "Sun Tzu",
 ur"レオニダス" : "Leonidas",
 ur"リュサンドロス" : "Lysander",
 ur"救済王プトレマイオス１世" : "Ptolemy I Soter",
 ur"チャンドラグプタ・マウリヤ" : "Chandragupta Maurya",
 ur"ハミルカル・バルカ" : "Hamilcar Barca",
 ur"ガイウス・マリウス" : "Gaius Marius",
 ur"スキピオ・アフリカヌス" : "Scipio Africanus",
 ur"ウェルキンゲトリクス" : "Vercingetorix",
 ur"アルミニウス" : "Arminius",
 ur"ブーディカ" : "Boudica",
 ur"曹操" : "Cao Cao",
 ur"諸葛亮" : "Zhuge Liang",
 ur"ベリサリウス" : "Belisarius",
 ur"ハリド・イブン・アル・ワリド" : "Khalid ibn al-Walid",
 ur"カルロ・マルテル" : "Charles Martel",
 ur"シャルルマーニュ" : "Charlemagne",
 ur"ジャヤヴァルマン２世" : "Jayavarman II",
 ur"エル・シド" : "El Cid",
 ur"征服王ウィリアム" : "William the Conqueror",
 ur"スブタイ" : "Subutai",
 ur"ティムール" : "Timur",
 ur"ジャンヌ・ダルク" : "Jeanne d'Arc",
 ur"パチャクテク" : "Pachacuti",
 ur"アウイツォトル" : "Auitzotl",
 ur"エルナン・コルテス" : "Hernan Cortes",
 ur"フランシスコ・ピサロ" : "Francisco Pizarro",
 ur"イワン雷帝" : "Ivan the Terrible",
 ur"ジャラルディン・ムハンマド・アクバル" : "Jalaluddin Muhammad Akbar",
 ur"グスタフ・アドルフ" : "Gustavus II Adolphus",
 ur"ミシェル・ド・ロイテル" : "Michiel de Ruyter",
 ur"オリバー・クロムウェル" : "Oliver Cromwell",
 ur"サヴォイ公オイゲン" : "Eugene of Savoy",
 ur"ホレーショ・ネルソン" : "Horatio Nelson",
 ur"ロバート・Ｅ・リー" : "Robert E. Lee",
 ur'ジェロニモ' : 'Geronimo',
 ur"山本五十六" : "Isoroku Yamamoto",
 ur"ジョージ・パットン" : "George Patton",
 ur"バーナード・モントゴメリー" : "Bernard Montgomery",
 ur"ハインツ・グーデリアン" : "Heinz Guderian",
 ur"エルヴィン・ロンメル" : "Erwin Rommel",
 ur"ゲオルギー・ジューコフ" : "Georgy Zhukov",
 ur"北条時宗" : "Hojo Tokimune",
 ur"織田信長" : "Oda Nobunaga",
 ur"豊臣秀吉" : "Toyotomi Hideyoshi",
 ur"島津義弘" : "Shimazu Yoshihiro",
 ur"本多忠勝" : "Honda Tadakatsu",
 ur"大山巌" : "Oyama Iwao",
 ur"東郷平八郎" : "Togo Heihachiro",
 ur"児玉源太郞" : "Kodama Gentaro",
 ur"今村均" : "Imamura Hitoshi",
 ur"呂尚" : "Jiang Ziya",
 ur"楽毅" : "Yue Yi",
 ur"白起" : "Bai Qi",
 ur"韓信" : "Han Xin",
 ur"項籍" : "Xiang Yu",
 ur"衛青" : "Wei Qing",
 ur"霍去病" : "Huo Qubing",
 ur"トウ禹" : "Deng Yu",
 ur"班超" : "Ban Chao",
 ur"周瑜" : "Zhou Yu",
 ur"李靖" : "Li Jing",
 ur"郭子儀" : "Guo Ziyi",
 ur"岳飛" : "Yue Fei",
 ur"孟キョウ" : "Meng Gong",
 ur"郭侃" : "Guo Kan",
 ur"徐達" : "Xu Da",
 ur"秦良玉" : "Qin Liangyu",
 ur"袁崇煥" : "Yuan Chonghuan",
 ur"鄭成功" : "Koxinga",
 ur"張自忠" : "Zhang Zizhong",
 ur"白崇禧" : "Zhang Zizhong",
 ur"朱徳" : "Zhu De",
 ur"冒頓単于" : "Modu Chanyu",
 ur"乙支文徳" : "Eulji Mundeok",
 ur"金ユ信" : "Kim Yushin",
 ur"大祚栄" : "Go of Balhae",
 ur"アグダ" : "Aguda",
 ur"耶律大石" : "Yelu Dashi",
 ur"バトゥ" : "Batu",
 ur"バヤン" : "Bayan",
 ur"ラームカムヘーン大王" : "Ram Khamhaeng the Great",
 ur"チャン・フン・ダオ" : "Tran Hung Dao",
 ur"李成桂" : "Yi Seong-gye",
 ur"姚広孝" : "Yao Guangxiao",
 ur"ラプ＝ラプ" : "Lapu-Lapu",
 ur"李舜臣" : "Yi Sun-sin",
 ur"ヌルハチ" : "Nurhaci",
 ur"金錫源" : "Kim Suk-won",
 ur"ヴォー・グエン・ザップ" : "Vo Nguyen Giap",
 ur"白善燁" : "Paik Sun-yup",
 ur"ハルパゴス" : "Harpagus",
 ur"カウティリヤ" : "Chanakya",
 ur"ミトリダテスⅥ世" : "Mithridates VI",
 ur"アムル・イブン・アル＝アース" : "Amr ibn al-As",
 ur"アブー・ムスリム" : "Abu Muslim",
 ur"アブド・アッラフマーンⅠ世" : "Abd ar-Rahman I",
 ur"ムハンマド・イブン・アビー・アーミル" : "Muhammad Ibn Abi Aamir",
 ur"トゥグリル・ベク" : "Togrul",
 ur"ザンギー" : "Zengi",
 ur"ヌールッディーン" : "Nur ad-Din",
 ur"バイバルス" : "Baibars",
 ur"オスマンⅠ世" : "Osman I",
 ur"アラー・ウッディーン・ハルジー" : "Alauddin Khilji",
 ur"バルバロス・ハイレディン" : "Barbaros Hayreddin",
 ur"アウラングゼーブ" : "Aurangzeb",
 ur"ナーディル・シャー" : "Nader Shah",
 ur"サモリ・トゥーレ" : "Samori Ture",
 ur"ラクシュミー・バーイー" : "Rani Lakshmibai",
 ur"ケマル・アタチュルク" : "Kemal Ataturk",
 ur"アフマド・シャー・マスード" : "Ahmad Shah Massoud",
 ur"アッティラ" : "Attila",
 ur"ヘラクレイオス" : "Heraclius",
 ur"ヨハネス・クルクアス" : "Johannes Kourkouas",
 ur"バシレイオスⅡ世" : "Basileios II",
 ur"クヌーズⅠ世" : "Cnut the Great",
 ur"アレクサンドル・ネフスキー" : "Alexander Nevsky",
 ur"ドミトリイ・ドンスコイ" : "Dmitry Donskoy",
 ur"ヤン・ジシュカ" : "Jan Zizka",
 ur"フニャディ・ヤーノシュ" : "Hunyadi Janos",
 ur"ヴラド・ツェペシュ" : "Vlad III",
 ur"スカンデルベグ" : "Skanderbeg",
 ur"イェルマーク" : "Yermak",
 ur"アルブレヒト・フォン・ヴァレンシュタイン" : "Albrecht von Wallenstein",
 ur"スタニスワフ・コニェツポルスキ" : "Stanislaw Koniecpolski",
 ur"ボフダン・フメリヌィーツィクィイ" : "Bohdan Khmelnytsky",
 ur"アレクサンドル・スヴォーロフ" : "Alexander Suvorov",
 ur"タデウシュ・コシチュシュコ" : "Tadeusz Kosciuszko",
 ur"ユゼフ・ピウスツキ" : "Jozef Pilsudski",
 ur"カール・グスタフ・マンネルヘイム" : "Carl Gustaf Mannerheim",
 ur"レフ・トロツキー" : "Leon Trotsky",
 ur"ヨシップ・ブロズ・チトー" : "Josip Broz Tito",
 ur"ミハイル・トゥハチェフスキー" : "Mikhail Tukhachevsky",
 ur"ダビデ" : "David",
 ur"テミストクレス" : "Themistocles",
 ur"エパメイノンダス" : "Epaminondas",
 ur"ピュロス" : "Pyrrhus",
 ur"フィリッポスⅡ世" : "Philippos II",
 ur"マルクス・アグリッパ" : "Marcus Agrippa",
 ur"ウェスパシアヌス" : "Vespasianus",
 ur"オットーⅠ世" : "Otto I",
 ur"アフォンソⅠ世" : "Afonso I",
 ur"ボードゥアン四世" : "Baldwin IV",
 ur"リチャードⅠ世" : "Richard I",
 ur"ウィリアム・ウォレス" : "William Wallace",
 ur"ロバートⅠ世" : "Robert I",
 ur"エドワード黒太子" : "Edward the Black Prince",
 ur"ベルトラン・デュ・ゲクラン" : "Bertrand du Guesclin",
 ur"ゴンサロ・デ・コルドバ" : "Gonzalo de Cordoba",
 ur"黒隊長ジョヴァンニ" : "Giovanni dalle Bande Nere",
 ur"フランシス・ドレーク" : "Francis Drake",
 ur"マウリッツ" : "Maurice of Nassau",
 ur"テュレンヌ子爵" : "Vicomte de Turenne",
 ur"ジョン・チャーチル" : "John Churchill",
 ur"ルイ＝ニコラ・ダヴー" : "Louis-Nicolas Davout",
 ur"ゲルハルト・フォン・シャルンホルスト" : "Gerhard von Scharnhorst",
 ur"カール・フォン・クラウゼヴィッツ" : "Carl von Clausewitz",
 ur"ウェリントン公アーサー・ウェルズリー" : "Arthur Wellesley",
 ur"ジュゼッペ・ガリバルディ" : "Giuseppe Garibaldi",
 ur"ヘルムート・フォン・モルトケ" : "Helmuth von Moltke",
 ur"フィリップ・ペタン" : "Philippe Ptain",
 ur"ヒュー・ダウディング" : "Hugh Dowding",
 ur"カール・デーニッツ" : "Karl Donitz",
 ur"エーリッヒ・フォン・マンシュタイン" : "Erich von Manstein",
 ur"ジョン・ポール・ジョーンズ" : "John Paul Jones",
 ur"イヤ・ナクアー＝テユシ・ナーナ" : "Eight Deer Jaguar Claw",
 ur"グラニー・ナニー" : "Granny Nanny",
 ur"トゥーサン・ルーヴェルチュール" : "Toussaint Louverture",
 ur"テカムセ" : "Tecumseh",
 ur"シモン・ボリバル" : "Simon Bolivar",
 ur"ユリシーズ・グラント" : "Ulysses S.Grant",
 ur"タシュンケ・ウィトコ" : "Thasunke Witko",
 ur"パンチョ・ビリャ" : "Pancho Villa",
 ur"チェスター・ニミッツ" : "Chester W.Nimitz",
 ur"ウィリアム・ハルゼー" : "William Halsey",
 ur"レイモンド・スプルーアンス" : "Raymond A.Spruance",
 ur"ヘンリー・アーノルド" : "Henry H.Arnold",
 ur"フィデル・カストロ" : "Fidel Castro",
 ur"チェ・ゲバラ" : "Che Guevara",

 ur'ペベッカメン' : 'Pebekkamen',
 ur'トラーキースのエフィアルテス' : 'Ephialtes of Trachis',
 ur'荊軻' : 'Jing Ke',
 ur'秦舞陽' : 'Qin Wuyang',
 ur'カリポス' : 'Calippus',
 ur'レオン・アルベルティ' : 'Leone Alberti',
 ur'ジョン・バーロウ' : 'John Barlow',
 ur'フランシス・ウォルシンガム' : 'Francis Walsingham',
 ur'服部半蔵' : 'Hattori Hanzo',
 ur'ヘラルト・バルタザル' : 'Balthasar Gerard',
 ur'アンソニー・バビントン' : 'Anthony Babington',
 ur'石川五右衛門' : 'Ishikawa Goemon',
 ur'ガスパル・グラツィアーニ' : 'Gaspar Graziani',
 ur'ガイ・フォークス' : 'Guy Fawkes',
 ur'ジョン・ハニーマン' : 'John Honeyman',
 ur'ネイサン・ヘイル' : 'Nathan Hale',
 ur'シャルロット・コルデー' : 'Charlotte Corday',
 ur'ジャコモ・カサノヴァ' : 'Giacomo Casanova',
 ur'アラン・ピンカートン' : 'Allan Pinkerton',
 ur'ウィリアム・メルヴィル' : 'William Melville',
 ur'ベル・ボイド' : 'Belle Boyd',
 ur'シドニー・ライリー' : 'Sidney Reilly',
 ur'安重根' : 'An Jung-Geun',
 ur'クロード・ダンシー' : 'Claude Dansey',
 ur'マタ・ハリ' : 'Mata Hari',
 ur'J. エドガー・フーヴァー' : 'J. Edgar Hoover',
 ur'モー・バーグ' : 'Moe Berg',
 ur'エセル・ローゼンバーグ' : 'Ethel Rosenberg',
 ur'ジュリアス・ローゼンバーグ' : 'Julius Rosenberg',
 ur'クラウス・フォン・シュタウフェンベルク' : 'Claus von Stauffenberg',
 ur'スザンヌ・スパーク' : 'Suzanne Spaak',
 ur'ウィリアム・ドノヴァン' : 'William Donovan',
 ur'マックス・ゴグフ' : 'Max Gogf',
 ur'賢者エイステイン' : 'Eystein the Wise',
 ur'スピーカー・ライオンハート' : 'Speaker the Lionhearted',
 ur'マーク・スイス' : 'Mark Swiss',
 ur'ダニエル・コール' : 'Daniel Cole',
 ur'ジョー・マティス' : 'Joe Matise',
 ur'アトラス・ティタヌス' : 'Atlas Titanus',
 ur'ノーラン・ブオナローティ' : 'Nolan Buonarroti',
 ur'フォシャン・デシーヴァー' : 'Foshaug the Deceiver',
 ur'ヴィクトル・グリフ' : 'Viktor Griph',
 ur'中臣鎌足' : 'Nakatomi no Kamatari',
 ur'間宮林蔵' : 'Mamiya Rinzo',
 ur'明石元二郎' : 'Akashi Motojiro',
 ur'北一輝' : 'Kita Ikki',
 ur'土肥原賢二' : 'Doihara Kenji',
 ur'新庄健吉' : 'Shinjo Kenkichi',
 ur'川島芳子' : 'Kawashima Yoshiko',
 ur'西施' : 'Xi Shi',
 ur'マルクス・ブルトゥス' : 'Marcus Brutus',
 ur'秦檜' : 'Qin Hui',
 ur'ハサン・サッバーフ' : 'Hassan-i Sabbah',
 ur'マリンチェ' : 'La Malinche',
 ur'マリュータ・スクラートフ' : 'Malyuta Skuratov',
 ur'ジョゼフ・フーシェ' : 'Joseph Fouche',
 ur'ハーバート・ヤードリー' : 'Herbert Yardley',
 ur'リヒャルト・ゾルゲ' : 'Richard Sorge',
 ur'エヴノ・アゼフ' : 'Yevno Azef',
 ur'ドラグーティン・ディミトリエビッチ' : 'Dragutin Dimitrijevic',
 ur'フェリックス・ジェルジンスキー' : 'Felix Dzerzhinsky',
 ur'ヴィドクン・クヴィスリング' : 'Vidkun Quisling',
 ur'トーマス・エドワード・ロレンス' : 'T.E.Lawrence',
 ur'マイケル・コリンズ' : 'Michael Collins',
 ur'戴笠' : 'Dai Li',
 ur'ウィリアム・ジョイス' : 'William Joyce',
 ur'レオポルド・トレッペル' : 'Leopold Trepper',
 ur'ラインハルト・ゲーレン' : 'Reinhard Gehlen',
 ur'オットー・スコルツェニー' : 'Otto Skorzeny',
 ur'サイモン・ヴィーゼンタール' : 'Simon Wiesenthal',
 ur'キム・フィルビー' : 'Kim Philby',
 ur'ジョルジュ・コワリ' : 'George Koval',
 ur'ウォルフガング・ロッツ' : 'Wolfgang Lotz',
 ur'マルクス・ヴォルフ' : 'Markus Wolf',
 ur'ギュンター・ギヨーム' : 'Gunter Guillaume',
 ur'フランソワ・ヴィドック' : 'Francois Vidocq',
 ur'ロージャ・シャーンドル' : 'Rozsa Sandor',
 ur'ジョン・ウィルクス・ボース' : 'John Wilkes Booth',
 ur'ナートゥラーム・ゴードゼー' : 'Nathuram Godse',
 ur'アレクサンドロス' : 'Alexander',
 ur'アショーカ' : 'Asoka',
 ur'アウグストゥス' : 'Augustus Caesar',
 ur'ビスマルク' : 'Bismarck',
 ur'ブーディカ' : 'Boudica',
 ur'ブレヌス' : 'Brennus',
 ur'エカテリーナ' : 'Catherine',
 ur'シャルルマーニュ' : 'Charlemagne',
 ur'チャーチル' : 'Churchill',
 ur'大キュロス' : 'Cyrus',
 ur'ダレイオス1世' : 'Darius I',
 ur'ド・ゴール' : 'De Gaulle',
 ur'エリザベス' : 'Elizabeth I',
 ur'フリードリッヒ' : 'Frederick',
 ur'ガンジー' : 'Gandhi',
 ur'チンギス・ハーン' : 'Genghis Khan',
 ur'ギルガメッシュ' : 'Gilgamesh',
 ur'ハンムラビ大王' : 'Hammurabi',
 ur'ハンニバル' : 'Hannibal',
 ur'ハトシェプスト' : 'Hatshepsut',
 ur'ワイナ・カパック' : 'Huayna Capac',
 ur'イザベル' : 'Isabella',
 ur'ジョアン2世' : 'Joao II',
 ur'ユリウス・カエサル' : 'Julius Caesar',
 ur'ユスティニアヌス1世' : 'Justinian I',
 ur'フビライ・ハーン' : 'Kublai Khan',
 ur'リンカーン' : 'Lincoln',
 ur'ルイ14世' : 'Louis XIV',
 ur'マンサ・ムサ' : 'Mansa Musa',
 ur'毛沢東' : 'Mao Zedong',
 ur'メフメド2世' : 'Mehmed II',
 ur'モンテスマ' : 'Montezuma',
 ur'ナポレオン' : 'Napoleon',
 ur'パカル2世' : 'Pacal II',
 ur'ペリクレス' : 'Pericles',
 ur'ピョートル' : 'Peter',
 ur'始皇帝' : 'Qin Shi Huang',
 ur'ラムセス2世' : 'Ramesses II',
 ur'ラグナル' : 'Ragnar',
 ur'ルーズヴェルト' : 'Roosevelt',
 ur'サラディン' : 'Saladin',
 ur'シャカ' : 'Shaka',
 ur'シッティング・ブル' : 'Sitting Bull',
 ur'スターリン' : 'Stalin',
 ur'スレイマン' : 'Suleiman',
 ur'スーリヤヴァルマン2世' : 'Suryavarman II',
 ur'徳川家康' : 'Tokugawa',
 ur'ヴィクトリア' : 'Victoria',
 ur'王建' : 'Wang Kon',
 ur'ワシントン' : 'Washington',
 ur'オラニエ公ヴィレム1世' : 'Willem van Oranje',
 ur'ザラ・ヤコブ' : 'Zara Yaqob',
}
